name: main

on:
  push:
    branches: [Master]

jobs:
  # validate:
  #   runs-on: ubuntu-latest
  #   name: Validate terraform
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: terraform validate
  #       uses: dflook/terraform-validate@v1
  #       id: validate
  #       with:
  #         path: terraform_code

  #     - name: Validate failed
  #       if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
  #       run: echo "terraform validate failed"

  # Lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   needs: validate
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v1

  #     - name: Run terraform fmt check
  #       run: terraform fmt -check -diff -recursive

    tfsec:
      name: tfsec sarif report
      runs-on: ubuntu-latest

      steps:
        - name: Clone repo
          uses: actions/checkout@master

        - name: tfsec
          uses: tfsec/tfsec-sarif-action@master
          with:
            working_directory: terraform_code
            github_token: ${{ secrets.GITHUB_TOKEN }}
            soft_fail: true
            sarif_file: tfsec.sarif

        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v2
          with:
            # Path to SARIF file relative to the root of the repository
            sarif_file: tfsec.sarif

    deploy:
      name: deploy new update 
      runs-on: ubuntu-latest
      needs: tfsec

      steps:
        - name: Clone repo
          uses: actions/checkout@master

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: ${{ env.aws_region }}
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        - name: S3 file Upload
          run: aws s3 cp terraform_code/index.html s3://${{ secrets.AWS_BUCKET }}
