name: main

on:
  push:
    branches: [Master]
env:
  aws_region: ap-southeast-1

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        id: validate
        with:
          path: terraform_code

      - name: Validate failed
        if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
        run: echo "terraform validate failed"

  Lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive

  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          working_directory: terraform_code
          github_token: ${{ secrets.GITHUB_TOKEN }}
          soft_fail: true
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif

  deploy:
    name: deploy new update
    runs-on: ubuntu-latest
    needs: tfsec

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws_region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: terraform_code/**

      - name: Upload file to S3 only file changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          aws s3 cp terraform_code/index.html s3://${{ secrets.AWS_BUCKET }}

      - name: start instance refresh only if file changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name sg-ASG-tf
